### ISSUE TITLE
document what's different

### ISSUE THREAD

**Issue by bbodenmiller** [scottzach1/fast-new-tab-redirect-reborn#1]
Why the reborn version? What's wrong with original?

**Comment by scottzach1** [comment]
Hey @bbodenmiller, 

Sadly I found that there wasn't many options for new tab redirectors that suited my needs.

I used to ping pong between [new tab redirect](https://chrome.google.com/webstore/detail/new-tab-redirect/icpgjfneehieebagbmdbhnlpiopdcmna) and [new tab reloader](https://chrome.google.com/webstore/detail/new-tab-changer/occbjkhimchkolibngmcefpjlbknggfh). I wasn't quite happy with either as I found them to be very slow (selecting and clearing the URL in the omni bar) and would constantly break. (Requiring me to ctrl + l on each new tab). I also didn't like the non-open source nature of the latter option.

Instead, I researched around and found the project [fast new tab redirect](https://chrome.google.com/webstore/detail/fast-new-tab-redirect/ohnfdmfkceojnmepofncbddpdicdjcoi?hl=en) and absolutely loved the speed and simplicity of it. Sadly, the last update was in 2016 (meaning that it has become stale) and I wished there was more features and a nicer design.

Currently, this implementation takes off from where that extension was left and re-skins the extension with dark theme and a new icon. In near future when I find the time I intend to configure syncing of the URL across browsers using the [chrome.storage](https://developer.chrome.com/extensions/storage) api. I also hope to add some other quality of life functionality such as a favourites list.

I will make sure to state this in my extension listing and `README.md` cheers :).

Cheers Z.

**Comment by scottzach1** [comment]
Explanation added to `README.md` in commit 34413dac888690be4abcb5b0c8ebf816e3bec37e
